### ISSUE TITLE
I can't get your attention lol

### ISSUE THREAD

**Issue by ekclifford** [CubeEngine/AuctionHouse#1]
I am ekclifford from bukkit.  You told me that I could take over this plugin for you.  But you never re-joined bukkit to make me a manager so I can add updated files....  Sorry this was the only way I could get to you.

ekclifford

**Comment by Faithcaio** [comment]
Yeah I am not using dev-bukkit anymore. The new SpongeAPI is way better to programm with.

Can't you just create a new page on there?

**Comment by ekclifford** [comment]
I can, yes.  But because I would be using most of the same code as you.  The plugin wouldn't be approved.  And I find that it would just be easier if you added me as an author to the auction house on dev.bukkit, so I can just continue the project.

**Comment by ekclifford** [comment]
I think it will just be easier to do that, because then I don't need bukkit to deny my plugin request.  And actually I could get banned if I just used your code and edited it.  I hope this makes sense, I really just want to fix it to work with 1.7+ so other people can continue to use it.

**Comment by Faithcaio** [comment]
I clearly stated that folks can fork this project. So why should you get banned for doing that.
And new files will have to get aproved anyways so...

Just make a new page.

**Comment by ekclifford** [comment]
I see where you are coming from....  It's just the plugin already has so many people that use it.  It gets a little complicated when there are so many different versions of the same plugin.  I'm not going to create a new version of it and post it as my own on bukkit.  I don't do that.  I just want to keep this plugin alive.  Just like I did for commandsforsale.  I hope you see where I'm coming from.
